name: 'Releez Finalize'

description: 'Finalize a GitHub release using Releez'

inputs:
  releez-version:
    description: 'Version of releez to use'
    required: false
    default: '0.1.0'
  version-override:
    description: 'Override for the next version, otherwise detect it from the repo context'
    required: false
    default: ''
  alias-tags:
    description: 'Type of alias tags to generate (none, major or minor)'
    required: false
    default: ''
  dry-run:
    description: 'If true, perform a dry run without tagging the release'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for authentication'
    required: false
    default: '${{ github.token }}'

outputs:
  release-version:
    description: 'The released version'
    value: ${{ steps.finalize-release.outputs.release-version }}
  release-notes:
    description: 'The release notes for the version'
    value: ${{ steps.finalize-release.outputs.release-notes }}
  release-preview:
    description: 'The preview output from a dry run. Empty if not a dry run.'
    value: ${{ steps.finalize-release.outputs.release-preview }}
  semver-versions:
    description: 'Generated semver versions'
    value: ${{ steps.generate-tags.outputs.semver-versions }}
  docker-versions:
    description: 'Generated Docker versions'
    value: ${{ steps.generate-tags.outputs.docker-versions }}
  pep440-versions:
    description: 'Generated PEP440 (Python) versions'
    value: ${{ steps.generate-tags.outputs.pep440-versions }}

runs:
  using: 'composite'
  steps:
    - name: Ensure uv
      run: |
        if ! command -v uv &> /dev/null
        then
          echo "uv could not be found, please install uv to proceed."
          exit 1
        fi
      shell: bash

    - name: Install releez as tool
      run: |
        uv tool install git+https://github.com/hotdog-werx/releez@${{ inputs.releez-version }}
      shell: bash

    - name: Git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Finalize release
      id: finalize-release
      run: |
        #!/bin/bash
        set -euo pipefail

        if [[ -n "${{ inputs.version-override }}" ]]; then
          versionOverrideArgs=(--version-override "${{ inputs.version-override }}")
        else
          versionOverrideArgs=()
        fi

        if [[ -n "${{ inputs.alias-tags }}" ]]; then
          aliasTagsArgs=(--alias-tags "${{ inputs.alias-tags }}")
        else
          aliasTagsArgs=()
        fi

        releaseNotes=$(uvx releez release notes ${versionOverrideArgs[@]})

        if [[ "${{ inputs.dry-run }}" == "true" ]]; then
          {
              echo "release-preview<<EOF"
              uvx releez release preview ${versionOverrideArgs[@]}
              echo "EOF"
          } >> $GITHUB_OUTPUT
        else
          uvx releez release tag  \
            ${versionOverrideArgs[@]} \
            ${aliasTagsArgs[@]} \
            --force
          {
              echo "release-preview="
          } >> $GITHUB_OUTPUT
        fi

        releaseVersion=$(uvx releez version artifact --is-full-release \
          ${versionOverrideArgs[@]} --alias-tags "none"
        )

        {
            echo "release-version=${releaseVersion}"
            echo "release-notes<<EOF"
            echo "$releaseNotes"
            echo "EOF"
        } >> $GITHUB_OUTPUT
      shell: bash

    - name: Generate Tags
      id: generate-tags
      uses: hotdog-werx/releez-version-artifact-action@v0
      with:
        releez-version: ${{ inputs.releez-version }}
        is-full-release: true
        version-override: ${{ inputs.version-override }}
        alias-tags: ${{ inputs.alias-tags }}
        github-token: ${{ inputs.github-token }}
